# Chargement de numpy

In [1]:
import numpy as np

# Creation des donnees avec numpy

# 1- Creation numpy array avec une liste ou une liste de liste(Matrice)

In [2]:
# Creation a partir d'une liste

liste = [1, 2, 3, 4, 5] # Definition de la liste d'elements
array_with_liste = np.array(liste)
print(array_with_liste) # Affiche le numpy array

[1 2 3 4 5]


In [4]:
# Creation a partir d'une Matrice

matrice = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
array_with_matrice = np.array(matrice)
print(array_with_matrice)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# 2- Creation d'un numpy array a partir des fonctions integrees

In [5]:
# Creation d'un numpy array a partir de la fonction zeros

array_zeros = np.zeros((3, 3))
print(array_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
# Creation d'un numpy array a partir de la fonction ones

array_ones = np.ones((3, 3))
print(array_ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [8]:
# Creation d'un array avec la fonction eye

array_eye = np.eye(3)
print(array_eye)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
# Creation d'un array avec la fonction arange : Pour creer des nombres avec le minimu et le maximum  avec un pas

array_arange = np.arange(0, 11, 1)
array_arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
# Creation d'un array avec la fonction linspace : Elle genere une sequence de nombre entre deux valeurs donnees avec un nombre de points donnees

array_linspace = np.linspace(0, 1, 5)
array_linspace

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [13]:
# Creation d'un array de valeurs aleatoires avec la fontion random

array_random = np.random.random((4, 3))
print(array_random)

[[0.3118316  0.07569387 0.81125176]
 [0.86501142 0.82008691 0.13396829]
 [0.18424819 0.90159638 0.21465838]
 [0.20995323 0.43995065 0.79339527]]


# Manipulation des matrices avec numpy

In [14]:
# Produit matriciel

matrice = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
produit_matriciel = np.dot(matrice, matrice)
print(produit_matriciel)

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [15]:
# Transposee

transposer = np.transpose(matrice)
print(transposer)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [16]:
# Inversion(Pour les matrices carrees non singulieres)

inverse = np.linalg.inv(array_eye)
print(inverse)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
# Determinant

determinant = np.linalg.det(matrice)
print(determinant)

6.66133814775094e-16


# Acceder aux elements, selectionner, modifier et mettre a jour un array numpy

In [18]:
# Acces aux elements

array1 = np.array([1, 2, 3, 4, 5])
premier_element = array1[0]
print(premier_element)

1


In [19]:
# Modification d'un element

array1[0] = 15
print(array1)

[15  2  3  4  5]


In [21]:
# Selection des elements qui respectent une condition

condition = array1 > 5
element_respectant_la_condition = array1[condition]
element_respectant_la_condition

array([15])

In [23]:
# Utilisation de np.where

condition = array1 > 3
condition
indices = np.where(condition)
indices

(array([0, 3, 4], dtype=int64),)

In [24]:
# Mise a jour d'un numpy array

array1[condition] = 0
print(array1)

[0 2 3 0 0]


In [25]:
# Slicing et indexation avancee

array6 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
premiere_ligne = array6[0, :]
premiere_ligne

array([1, 2, 3])

In [26]:
# Premiere colonne

premiere_colonne = array6[:, 0]
premiere_colonne

array([1, 4, 7])

In [27]:
# Sous matrice

sous_matrice = array6[1:3, 1:3]
sous_matrice

array([[5, 6],
       [8, 9]])

In [28]:
# Indexation avancee

lignes = [0, 1]
colonnes = [1, 2]
elements_selectionnes = array6[lignes, colonnes]
elements_selectionnes

array([2, 6])

In [29]:
# Operations elementaires et diffusions(Broadcasting)

array7 = np.array([1, 2, 3])
array8 = np.array([4, 5, 6])

In [31]:
# Addition elementaire

array_addition = array7 + array8
array_addition

array([5, 7, 9])

In [34]:
# Multiplication elementaire

array_multiplication = array7 * array8
array_multiplication

array([ 4, 10, 18])

In [35]:
# Diffusion(broadcasting)

array9 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array10 = np.array([1, 2, 3])
array9 + array10

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

# Redimensionnement, append, type de donnees, taille, etc...

In [39]:
# Redimmensionner le numpy array

array3 = np.arange(9)
array3_redimensioner = array3.reshape((3, 3))
print(array3_redimensioner)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [41]:
# Ajouter les elements dans un numpy array

array1_allonge = np.append(array1, [6,7,8])
print(array1_allonge)

[0 2 3 0 0 6 7 8]


In [42]:
# Connaitre les caracteristiques d'un numpy array

array_with_matrice.shape # Dimension de l'array

(3, 3)

In [43]:
# Connaitre le type de l'objet

type(array_with_matrice)

numpy.ndarray

In [44]:
# Connaitre le type des elements

array1.dtype

dtype('int32')